language: python
cache: pip

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
sudo: required

branches:
  only:
  - master
  - develop

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests
script:
  pytest --cov=libsbgnpy
after_success:
  coveralls