language: python

branches:
  only:
  - master
  - develop

python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "nightly"

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
script: nosetests