language: python

branches:
  only:
  - master
  - develop

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests
script:
  # nosetests
  nosetests --with-coverage --cover-package=libsbgnpy
after_success:
  coveralls

# nosetests --with-coverage --cover-package=libsbgnpy